### ISSUE TITLE
Hello brother, sorry for open an issue.

### ISSUE THREAD

**Issue by lucasmz1** [oSoWoSo/DistroHopper#28]
I saw today in my github you made a pull request, what do you need exactly me to do?
is something wrong with my qemu build?

**Comment by zen0bit** [comment]
Why not comment there?

Nothing wrong.
I still wanna use it as starting point for q (quickemu) bundled in appimage
Just to be more reabable, usable for my attempts

**Comment by lucasmz1** [comment]
oh that's good, good work, indeed my code is messy. that's why there are so many stuff.
when you got some time add me in your telegram zainotel.
let's discus some stuff to improve our projects.
