### ISSUE TITLE
"DistroHooper" typo on README.md, line 5

### ISSUE THREAD

**Issue by hypnoshh** [oSoWoSo/DistroHopper#3]
Line 5 on README.md has a typo in the name and URL:
`# [DistroHooper](https://github.com/oSoWoSo/DistroHooper)`

Should be:
`# [DistroHopper](https://github.com/oSoWoSo/DistroHopper)`

Looks like an awesome project!

**Comment by zen0bit** [comment]
Thanks for help!
You are awesome 👌
